name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - uses: actions/checkout@v2
      
      - name: Install dependencies
        working-directory: ./vue-todo
        run: npm install
        
      - name: Build
        working-directory: ./vue-todo
        run: npm run build && npm run zip
    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: vue-todo-zip
          path: ./vue-todo/build/*.zip
    
