name: Upload Release Asset

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - uses: actions/checkout@v2

      - name: Install dependencies for Vue
        working-directory: ./vue-todo
        run: npm install

      - name: Build for Vue
        id: build_vue
        working-directory: ./vue-todo
        run: |
          npm run build
          npm run zip
          echo "::set-output name=filename::$(ls ./build)"

      - name: Install dependencies for React
        working-directory: ./react-todo
        run: npm install

      - name: Build for React
        id: build_react
        working-directory: ./react-todo
        run: |
          npm run build
          npm run zip
          echo "::set-output name=filename::$(ls ./build)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset for Vue
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vue-todo/build/${{steps.build_vue.outputs.filename}}
          asset_name: ${{steps.build_vue.outputs.filename}}
          asset_content_type: application/zip

      - name: Upload Release Asset for React
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./react-todo/build/${{steps.build_react.outputs.filename}}
          asset_name: ${{steps.build_react.outputs.filename}}
          asset_content_type: application/zip
